### ISSUE TITLE
Not working for some URLs

### ISSUE THREAD

**Issue by andyneff** [Racle/undisposition#1]
While this extension does work occasionally, I still notice many times when it does not:

Here's the latest example is: https://avlab.com.tw/products/download/.-uploads-file-product-AVLT_SD01_SD03_INSTALLATION_MANUAL.pdf

Here's an excerpt from the headers in chrome:

```
content-disposition: attachment; filename="AVLT_SD01_SD03_INSTALLATION_MANUAL.pdf"
content-length: 2863387
content-transfer-encoding: binary
content-type: application/octet-stream
```

(Headers from the Chrome debugger)
Chrome 92.0.4515.159

---

Here's an example off of an internal server where Undisposition does work as expected:

```
Content-Disposition: attachment; filename=data.txt
Content-Type: text/plain
```

**Comment by Racle** [comment]
Hey,
This is fixed by https://github.com/Racle/undisposition/commit/41866b304c64a563d917e3c2c6a747254a6c9f11

New version of extension is available on Firefox addons page right now and soon in chrome extensions page (going trough review, will be automatically released when that's done).
