### ISSUE TITLE
Allow whitelisting some websites

### ISSUE THREAD

**Issue by martin-braun** [Racle/undisposition#2]
There are cases where Undisposition is not useful. For instance when downloading a certificate from Apple's [Certificate, Identifiers & Profiles](https://developer.apple.com/account/resources/certificates/). This is just one case. Some websites fail to provide the right headers so this extension can't work out what is binary or not, thus attempting to show binary data as text or naming the filename wrong.

In case of Apples certificate website, it names the *.cer file "downloadCertificateContent.action", which is wrong.

Being able to white list critical websites would give more control to the user.

**Comment by nihaals** [comment]
Another example of a site that stops working is Google Drive

**Comment by Racle** [comment]
I'll look into this andI do not promise any time frame for this.

And If/when I get this done, this feature is coming as right click menu option as I do want to keep extension icon as fast toggle.

Currently extension is checking URL and getting extension from that (very simple solution).
If that extension finds [commonly used extensions](https://github.com/Racle/undisposition/commit/41866b304c64a563d917e3c2c6a747254a6c9f11#diff-0d6f9bc11f0471e8c4a2b32277069bf47c2e73027697ff5cc7b117ae3642db16R24-R26), it has checks for those.

**Comment by martin-braun** [comment]
@Racle Thanks, yes, you don't have to provide any ETA, I'm thankful for this extension nonetheless. Often I can simply press CMD+S to store the file anyway. In case of wrong filenames, I can also just rename the file to what it should supposed to be. However, a few times I fell in this pitfall, because I forgot.

I agree that a context menu implementation is enough. A dev who discovers problems will attempt to try to right click to find a white list feature anyway.

Thanks for your fork.

**Comment by nihaals** [comment]
Having a default blacklist could be helpful in instances where downloading just doesn't work. For example, with Google Drive, you get an error about third party cookies not being enabled and there is no other way to download the file. Since the error message is wrong, it will likely lead to people looking into different solutions without thinking this was the cause.

**Comment by orschiro** [comment]
Same issue for me. 

It sadly breaks Google Drive download.

Doesn't happen if I disable the extension.

![image](https://user-images.githubusercontent.com/170947/174582194-3fd11692-8f43-4064-84bf-0f5e54307b05.png)

**Comment by Racle** [comment]
@martin-braun @nihaals @orschiro 
Just uploaded version 0.0.5 with (very simple) blacklist to Firefox and Chrome web stores.
You can find Settings by right clicking extension icon.

This should be approved soon.

Chrome version also has manifest v3 support, so that should work even after that is forced.

**Comment by orschiro** [comment]
Nice, thank you!

**Comment by nihaals** [comment]
I'm not sure if Manifest v3 supports it, but it would be nice to be able to use the browser's built-in settings button too (`options_page`/`options_ui`) to stay consistent with other extensions.

**Comment by nihaals** [comment]
Created as #4

**Comment by martin-braun** [comment]
@Racle Should we maintain a proper default black list? I see apple.com and google.com made it, but dropbox.com and potentially more websites are affected, especially those that offer a preview of the file by default.

**Comment by orschiro** [comment]
Or maybe also interesting to have a whitelist feature?

Meaning disable always except for those whitelisted pages.

In my case, I have only one site where I need it and the rest of the time I
want it to be disabled to prevent issues.
