### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by RobertoUa** [Racle/undisposition#3]

**Comment by Racle** [comment]
It's working on Chrome Version 105.0.5195.127 and Firefox Version 106.0b2 (64-bit).

Do you have extension enabled and turned on? (blue box at top right corner of extension)

If yes, I'm going to need more information about Operating System and Browser to see if I can replicate this issue.

**Comment by RobertoUa** [comment]
Chrome Version 106.0.5249.40 (Official Build) beta (x86_64)
Mac OS 12.6

yes, it has blue blox

**Comment by Racle** [comment]
It might be something to do with beta version of chrome. 

Not 100% sure, but it might already use and enforce Manifest V3 which could potentially break this extension.

I'll look into it, but I don't have any ETA for fix (if there is way to fix this).

**Comment by Racle** [comment]
@RobertoUa 
Just uploaded new version (0.0.5) to chrome web store. Extension now has manifest V3 support (and very simple blacklist feature).
That should be approved soon.
